### ISSUE TITLE
Detect user-selected page

### ISSUE THREAD

**Issue by t-cth** [csu-hci-projects/FA23-FoldAR-Step-by-step-Instructions-for-Folding-Paper-Models-in-AR#18]
https://developer.apple.com/documentation/arkit/arkit_in_ios/content_anchors/visualizing_and_interacting_with_a_reconstructed_scene#3562538

https://developer.apple.com/documentation/arkit/arkit_in_ios/content_anchors/tracking_and_visualizing_planes

**Comment by ibapps39** [comment]
🛑 '->' means “related” to what's above it in bold, italics

***Apple's Demo***
[Detecting Images in an AR Experience React to known 2D images in the user’s environment, and use their positions to place AR content](https://developer.apple.com/documentation/arkit/arkit_in_ios/content_anchors/detecting_images_in_an_ar_experience)
-> https://developer.apple.com/documentation/arkit/arkit_in_ios/content_anchors/detecting_images_in_an_ar_experience
- *Many AR experiences can be enhanced by using known features of the user’s environment to trigger the appearance of virtual content. For example, a museum app might show a virtual curator when the user points their device at a painting, or a board game might place virtual pieces when the player points their device at a game board.*
- *This example app looks for any of the several reference images included in the app’s asset catalog. When ARKit detects one of those images, the app shows a message ***identifying the detected image and a brief animation showing its position in the scene***.*

<h3> 2D Image Recognition Route </h3>
<p>Config the session’s (see ARConfiguration) detectionImages property array by passing it a collection of reference images (ARReferenceImage), ARReferenceImages auto creates an ARImageAnchor and the detected image by the ARImageAnchor references referenceImage (which is an ARReferenceImage object).

***ARConfiguration***
- The base object that contains information about how to configure an augmented reality session.
- https://developer.apple.com/documentation/arkit/arconfiguration

-> Configuring the image tracking
- ```class ARImageTrackingConfiguration : ARConfiguration```
- A configuration that tracks known images using the rear-facing camera.
-  https://developer.apple.com/documentation/arkit/arimagetrackingconfiguration

-> ARImageTrackingConfiguration
- ```var trackingImages: Set<ARReferenceImage>```
-  A set of images that ARKit searches for and tracks in the user's environment.
- ```init()``` then ```var trackingImages: [Set](https://developer.apple.com/documentation/swift/set)<[ARReferenceImage](https://developer.apple.com/documentation/arkit/arreferenceimage)> { get set }```
- ‼️**Performance tips + info** ‼️https://developer.apple.com/documentation/arkit/arimagetrackingconfiguration …
Such as ⚠️*World tracking has a higher performance cost than image-only tracking, so your session can reliably track more images at once with ARImageTrackingConfiguration.*⚠️

***detectionImage***
- DetectionImage is an array of ARReferenceImage images you want to detect
- To enable image detection in AR *pass a collection of reference images(ARReferenceImage’s) to your session configuration's [detectionImages](https://developer.apple.com/documentation/arkit/arworldtrackingconfiguration/2941063-detectionimages) property.*/array.
- ```var detectionImages: Set<ARReferenceImage>! { get set }```

***ARReferenceImage***
- A **2D** image that you want ARKit to detect in the physical environment.
- ```class ARReferenceImage : NSObject```
->  Function to Load Reference Images is
```class func referenceImages(inGroupNamed: String, bundle: Bundle?) -> Set<ARReferenceImage>?```
- where inGroupNamed is a AR Resource Group in your Xcode project's asset catalog.
-> Validating Reference Images Function
- ```func validate(completionHandler: (Error?) -> Void)```
- Determines whether the reference image is valid.

***ARImageAnchor***
- An anchor for a known image that ARKit detects in the physical environment.
- ```class ARImageAnchor : ARAnchor```
-  **At runtime**, *ARKit generates an ARAnchor for a real-world object it recognizes, which allows an app to refer to its details, such as size and physical location.*

***referenceImage***
- The detected image referenced by the image anchor.
- ```var referenceImage: ARReferenceImage { get }```

**Comment by tc30** [comment]
document segmentation: https://developer.apple.com/documentation/vision/vndetectdocumentsegmentationrequest

**Comment by tc30** [comment]
VNDetectDocumentSegmentationRequest usage:

        let test = VNDetectDocumentSegmentationRequest()
     
        let doc = test.results
        
        doc?.first?.topRight
