### ISSUE TITLE
Tracking accuracy metric

### ISSUE THREAD

**Issue by t-cth** [csu-hci-projects/FA23-FoldAR-Step-by-step-Instructions-for-Folding-Paper-Models-in-AR#38]

**Comment by t-cth** [comment]
Mathematical equation that correlates relative finger joint locations?

**Comment by t-cth** [comment]
Equation for finger's range of motion?

**Comment by tc30** [comment]
Distances between each finger tip

**Comment by tc30** [comment]
Measuring accuracy of 'rectangles' on folded paper
