### ISSUE TITLE
Fold metrics

### ISSUE THREAD

**Issue by t-cth** [csu-hci-projects/FA23-FoldAR-Step-by-step-Instructions-for-Folding-Paper-Models-in-AR#39]
Can you detect/recognize each fold in a sequence based on the positions of the points of the fingers?

**Comment by t-cth** [comment]
- Based on starting and ending positions of all finger points, can we determine if the fold performed by the user was fold 1, fold 2, etc.?

**Comment by t-cth** [comment]
Compare deviation of each fold's area to (expected) half of original paper.

**Comment by tc30** [comment]
Plotting mean distance of fingertips across all frames included here ?
